apiVersion: v1
kind: Pod
metadata:
  name: customer-pod
  # namespace: projecta
  labels:
    app: packersmovers    
spec:
  containers:
  - name: customer
    image: 931846072502.dkr.ecr.us-east-1.amazonaws.com/customer
    ports:
    - containerPort: 8080
  - name: webapp
    image: nginx
    ports:
    - containerPort: 80

